In [2]:
#理解nonzero
import numpy as np

ylist = [0, 0, 1, 0, 1, 1]
list_np = np.array(ylist)
list_np
yvalid = np.nonzero(list_np)
print("yvalid= ", yvalid)
x = np.random.choice(yvalid[0].tolist())

yvalid=  (array([2, 4, 5], dtype=int64),)


In [18]:
y_m = np.zeros((12, 3, 12))
y_m[5, 1, 1]=99
y_m[0, 2, 1]=100
y_m[2, 2, 2]=101
y_m
y_nz = np.nonzero(y_m)
ax0, ax1, ax2 = y_nz #ax0, ax1, ax2三个数组的len()是相等的。
print(f"{ax0}\n{ax1}\n{ax2}")
# ax0代表axis 0, 其中的元素是y_m中的非零值在ax0上的下标, 并且按照下标值的大小排序。
# ax1代表axis 1, ax2代表axis 2
# [ax0[i], ax1[i], ax2[i]]在y_m中定位了一个非零的值。

[0 2 5]
[2 2 1]
[1 2 1]


In [21]:
y_m_1 = np.ones((12, 3, 12))
y_nz = np.nonzero(y_m_1)
ax0, ax1, ax2 = y_nz #ax0, ax1, ax2三个数组的len()是相等的。
len(ax0)  #因为有12*3*12=432个非零的值, 所以得到 432

432

In [19]:
player_limit = {
    'wheat_field': 10,
    'apple_orchard': 6,
    'ranch': 6,
    'forest': 6,
    'mine': 6,
    'fruit&veg_market': 6,
    'cheese_factory': 6,
    'furniture_factory': 6,
    'bakery': 10,
    'convenience_store': 6,
    'cafe': 6,
    'family_restaurant': 6,
    'stadium': 1,
    'tv_station': 1,
    'business_center': 1,
    'shopping_mall': 1,
    'station': 1,
    'amusement_park': 1,
    'radio_tower': 1
}
#BUILDING_ORDER = list(player_limit.keys())
BUILDING_ORDER = [*player_limit]  #  注意*的使用
print(type(BUILDING_ORDER))
BUILDING_ORDER.sort()
BUILDING_ORDER


<class 'list'>


['amusement_park',
 'apple_orchard',
 'bakery',
 'business_center',
 'cafe',
 'cheese_factory',
 'convenience_store',
 'family_restaurant',
 'forest',
 'fruit&veg_market',
 'furniture_factory',
 'mine',
 'radio_tower',
 'ranch',
 'shopping_mall',
 'stadium',
 'station',
 'tv_station',
 'wheat_field']

In [30]:
choice_list = [0, 3, 4, 6, 10, 18]
choice_list[:-1] # :-1

[0, 3, 4, 6, 10]

In [39]:
import os


def write_g_id(g_id):
    g_id = str(g_id)
    cwd = os.getcwd()  # C:\Users\maxyi\ai\deepsims
    g_settings_path = os.path.join(cwd, "g_settings.py")

    line_index = 0
    with open(g_settings_path, 'r') as f:
        lines = f.readlines()
        for i in range(len(lines)):
            if "last_g_id" in lines[i]:
                lines[i] = f"last_g_id = {g_id}"
                break

    with open(g_settings_path, 'w') as f:
        for i in range(len(lines)):
            if lines[i]!='':
                f.write(lines[i]+'\n')

    return


def get_g_id():
    cwd = os.getcwd()  # C:\Users\maxyi\ai\deepsims
    g_settings_path = os.path.join(cwd, "g_settings.py")
    with open(g_settings_path, 'r') as f:
        lines = f.readlines()
        for i in lines:
            if "last_g_id" in i:
                i_list = i.split(' ')
                g_id = int(i_list[-1])
                return g_id


print(get_g_id())
write_g_id(123)


999


In [5]:
import pandas as pd
from copy import deepcopy


p0_bld = {'wheat_field': 2, 'apple_orchard': 5, 'ranch': 4, 'forest': 0, 'mine': 1, 'fruit&veg_market': 3, 'cheese_factory': 0, 'furniture_factory': 0, 'bakery': 1, 'convenience_store': 1, 'cafe': 1, 'family_restaurant': 0, 'stadium': 0, 'tv_station': 1, 'business_center': 0, 'shopping_mall': 1, 'station': 1, 'amusement_park': 1, 'radio_tower': 1}
p1_bld = {'wheat_field': 1, 'apple_orchard': 0, 'ranch': 0, 'forest': 0, 'mine': 4, 'fruit&veg_market': 1, 'cheese_factory': 0, 'furniture_factory': 0, 'bakery': 4, 'convenience_store': 4, 'cafe': 2, 'family_restaurant': 3, 'stadium': 1, 'tv_station': 1, 'business_center': 1, 'shopping_mall': 1, 'station': 0, 'amusement_park': 1, 'radio_tower': 1}
p2_bld = {'wheat_field': 5, 'apple_orchard': 0, 'ranch': 2, 'forest': 1, 'mine': 0, 'fruit&veg_market': 2, 'cheese_factory': 1, 'furniture_factory': 3, 'bakery': 2, 'convenience_store': 0, 'cafe': 2, 'family_restaurant': 2, 'stadium': 1, 'tv_station': 1, 'business_center': 1, 'shopping_mall': 0, 'station': 0, 'amusement_park': 0, 'radio_tower': 0}
p3_bld = {'wheat_field': 2, 'apple_orchard': 1, 'ranch': 0, 'forest': 2, 'mine': 0, 'fruit&veg_market': 0, 'cheese_factory': 2, 'furniture_factory': 3, 'bakery': 3, 'convenience_store': 1, 'cafe': 1, 'family_restaurant': 1, 'stadium': 1, 'tv_station': 0, 'business_center': 1, 'shopping_mall': 1, 'station': 1, 'amusement_park': 0, 'radio_tower': 0}
supply_bld = {'wheat_field': 2, 'apple_orchard': 1, 'ranch': 0, 'forest': 2, 'mine': 0, 'fruit&veg_market': 0, 'cheese_factory': 2, 'furniture_factory': 3, 'bakery': 3, 'convenience_store': 1, 'cafe': 1, 'family_restaurant': 1, 'stadium': 1, 'tv_station': 0, 'business_center': 1, 'shopping_mall': 1, 'station': 1, 'amusement_park': 0, 'radio_tower': 0}

# deepcopy
p0_bldg = deepcopy(p0_bld)
p1_bldg = deepcopy(p1_bld)
p2_bldg = deepcopy(p2_bld)
p3_bldg = deepcopy(p3_bld)
supply_bldg = deepcopy(supply_bld)

#每个字典增加一个coins键-值对
p0_bldg['coins'] = 3
p1_bldg['coins'] = 4
p2_bldg['coins'] = 5
p3_bldg['coins'] = 6
supply_bldg['coins'] = 0


#将字典转换为序列
ser0 = pd.Series(p0_bldg)
ser1 = pd.Series(p1_bldg)
ser2 = pd.Series(p2_bldg)
ser3 = pd.Series(p3_bldg)
supply = pd.Series(supply_bldg)

#将序列合成DataFrame
df = pd.DataFrame({'p0':ser0, 'p1':ser1, 'p2':ser2, 'p3':ser3, 'supply': supply})

print(df)

                   p0  p1  p2  p3  supply
wheat_field         2   1   5   2       2
apple_orchard       5   0   0   1       1
ranch               4   0   2   0       0
forest              0   0   1   2       2
mine                1   4   0   0       0
fruit&veg_market    3   1   2   0       0
cheese_factory      0   0   1   2       2
furniture_factory   0   0   3   3       3
bakery              1   4   2   3       3
convenience_store   1   4   0   1       1
cafe                1   2   2   1       1
family_restaurant   0   3   2   1       1
stadium             0   1   1   1       1
tv_station          1   1   1   0       0
business_center     0   1   1   1       1
shopping_mall       1   1   0   1       1
station             1   0   0   1       1
amusement_park      1   1   0   0       0
radio_tower         1   1   0   0       0
coins               3   4   5   6       0


In [15]:
RGBP_ORDER = ['cafe', 'family_restaurant', 'bakery', 'convenience_store', 'cheese_factory', 'furniture_factory', 'fruit&veg_market', 'ranch', 'forest', 'mine', 'wheat_field','apple_orchard', 'stadium', 'tv_station', 'business_center', 'station', 'shopping_mall', 'amusement_park', 'radio_tower']

RGBP_STRIP = [RGBP_ORDER[i].strip() for i in range(len(RGBP_ORDER))]
RGBP_STRIP
rows = RGBP_STRIP + ['coins']
print(rows)

['cafe', 'family_restaurant', 'bakery', 'convenience_store', 'cheese_factory', 'furniture_factory', 'fruit&veg_market', 'ranch', 'forest', 'mine', 'wheat_field', 'apple_orchard', 'stadium', 'tv_station', 'business_center', 'station', 'shopping_mall', 'amusement_park', 'radio_tower', 'coins']


In [16]:
vals = [[] for _ in range(4)]
vals

[[], [], [], []]

In [28]:
BUILDING_ORDER = ['cafe',
 'family_restaurant',
 'bakery',
 'convenience_store',
 'cheese_factory',
 'furniture_factory',
 'fruit&veg_market',
 'ranch',
 'forest',
 'mine',
 'wheat_field',
 'apple_orchard',
 'stadium',
 'tv_station',
 'business_center',
 'station',
 'shopping_mall',
 'amusement_park',
 'radio_tower']

supply_buildings = {
    'wheat_field': 6,
    'apple_orchard': 6,
    'ranch': 6,
    'forest': 6,
    'mine': 6,
    'fruit&veg_market': 6,
    'cheese_factory': 6,
    'furniture_factory': 6,
    'bakery': 6,
    'convenience_store': 6,
    'cafe': 6,
    'family_restaurant': 6,
    'stadium': 4,
    'tv_station': 4,
    'business_center': 4,
    'shopping_mall': 4,
    'station': 4,
    'amusement_park': 4,
    'radio_tower': 4}

building_cost = {
    'wheat_field': 1,
    'apple_orchard': 3,
    'ranch': 1,
    'forest': 3,
    'mine': 6,
    'fruit&veg_market': 2,
    'cheese_factory': 5,
    'furniture_factory': 3,
    'bakery': 1,
    'convenience_store': 2,
    'cafe': 2,
    'family_restaurant': 3,
    'stadium': 6,
    'tv_station': 7,
    'business_center': 8,
    'shopping_mall': 10,
    'station': 4,
    'amusement_park': 16,
    'radio_tower': 22
}

supply_val = [supply_buildings[BUILDING_ORDER[i]] for i in range(len(BUILDING_ORDER))] + [100]
print(supply_val)
sum(supply_val[:-1])

bld_cost = [building_cost[BUILDING_ORDER[i]] for i in range(len(BUILDING_ORDER))] + [999]
print(bld_cost)
sum(bld_cost[:-1])
x=[supply_val[i]*bld_cost[i] for i in range(len(bld_cost))]
sum(x[:-1])

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 4, 100]
[2, 3, 1, 2, 5, 3, 2, 1, 3, 6, 1, 3, 6, 7, 8, 4, 10, 16, 22, 999]


484

In [29]:
x = [1]*len(rows)
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [53]:
from random import choice
nplayers=4
cand_ix = [i+1 for i in range(nplayers)]
print(cand_ix[:-1])
ychoice = choice(cand_ix[:-1])
ychoice

[1, 2, 3]


2

In [54]:
lst = [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 4, 100]
print(set(lst))

{100, 4, 6}
